config/routes.rb
Rails.application.routes.draw do


  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'


  # get 'admin_users/index'
  # get 'admin_users/new'
  # get 'admin_users/edit'
  # get 'admin_users/delete'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
      member do
        get :delete
      end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages_controller do
    member do
      get :delete
    end
  end

  resources :sections_controller do
    member do
      get :delete
    end
  end

  get 'example_controller/home'
  get 'example_controller/hall'

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'

  #root 'example_controller#home'

  #This is default route and it may go away on future Rails
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/pages_controller_controller.rb
class PagesControllerController < ApplicationController

  layout 'admin'
  before_action :confirm_logged_in
  before_action :find_subject
  before_action :set_page_count, :only => [:new, :create, :edit, :update]

  def index
    @pages = @subject.pages.sorted
  end

  def show
    @page = Page.find_by_id(params[:id])
  end

  def new
    @page = Page.new(:subject_id => @subject.id)
  end

  def create
    @page = Page.new(page_params)
    @page.subject_id = @subject
    if @page.save
      flash[:notice] = "Subject created successfully !!"
      redirect_to(pages_controller_index_path(:subject_id => @subject.id))
    else
      render('new')
    end
  end

  def edit
    @page = Page.find(params[:id])
  end

  def update
    @page = Page.find(params[:id])
    if @page.update_attributes(page_params)
      flash[:notice] = "Page updated successfully"
      redirect_to(pages_controller_path(@page, :subject_id => @subject.id))
    else
      render('edit')
    end
  end

  def delete
    @page = Page.find(params[:id])
  end

  def destroy
    @page = Page.find(params[:id])
    @page.destroy
    flash[:notice] = "#{@page.name} destroyed successfully"
    redirect_to(pages_controller_index_path(:subject_id => @subject.id))
  end

  private

  def page_params
    params.require(:page).permit(:name, :permalink, :position, :visible)
  end

  def find_subject
    @subject = Subject.find(params[:subject_id])
  end

  def set_page_count
    @page_count = @subject.pages.count
    if params[:action] == 'new' || params[:action] == 'create'
      @page_count += 1
    end
  end
end

app/helpers/pages_controller_helper.rb
module PagesControllerHelper
end

app/views/pages_controller/_form.html.erb
<%= error_messages_for(f.object)%>

<table summary = "Page Form Fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name)%></td>
  </tr>
  <tr>
    <th>Subject</th>
    <td><%= f.object.subject.name%></td>
  </tr>
  <tr>
    <th>Permalink</th>
    <td><%= f.text_field(:permalink)%></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@page_count)%></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible)%></td>
  </tr>
</table>

app/views/pages_controller/delete.html.erb
<% @page_title = "Delete Page" %>
<%=link_to('Back to list', pages_controller_index_path(:subject_id => @subject.id), :class => 'back-line') %>

<div class="pages delete">
  <h2>Delete Page</h2>
  <%= form_for(@page, :url => pages_controller_path(@page, :subject_id => @subject.id), :method => 'delete') do |f|%>
  <p>Are you sure you want to permanently delete this page ?</p>
  <p class="reference-name"><%=f.object.name%></p>
  <div class="form-button">
    <%=f.submit("Delete page")%>
  </div>
  <%end%>
</div>

app/views/pages_controller/edit.html.erb
<% @page_title = "Edit Page" %>
<%=link_to('Back to list', pages_controller_index_path(:subject_id => @subject.id), :class => 'back-line') %>
<div class="page new">
  <h2>Edit Page</h2>
    <%=form_for(@page, :url => pages_controller_path(@page, :subject_id => @subject.id)) do |f| %>
      <%= render(:partial => 'form', :locals => {:f => f})%>
      <div class="form-buttons">
        <%= f.submit("Update Page")%>
      </div>
    <% end %>
</div>

app/views/pages_controller/index.html.erb
<% @page_title = "All Pages" %>

<%= link_to("<< Back to Subjects", subjects_path) %>

<div class="pages index">
  <h2>Pages</h2>
  <%=link_to("Add new page",new_pages_controller_path(:subject_id => @subject.id),:class => 'action new')%>
  <table class="listing" summary="Pages List">
    <tr class="header">
      <th>#</th>
      <th>Subject_ID</th>
      <th>Page</th>
      <th>Permalink</th>
      <th>Visible</th>
      <th>Action</th>
    </tr>
    <% @pages.each do |page| %>
    <tr>
      <td><%= page.position %></td>
      <td><%= page.subject_id%></td>
      <td><%= page.name%></td>
      <td><%= page.permalink%></td>
      <td class="center"><%= status_tag(page.visible) %></td>
      <td class="actions">
          <%= link_to("View Sections", sections_controller_index_path(:page_id => page.id))%>
          <%=link_to("Show", pages_controller_path(page, :subject_id => @subject.id), :class => 'action_show') %>
          <%=link_to("Edit", edit_pages_controller_path(page, :subject_id => @subject.id), :class => 'action_edit') %>
          <%=link_to("Delete", delete_pages_controller_path(page, :subject_id => @subject.id), :class => 'action_delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/pages_controller/new.html.erb
<% @page_title = "New Page" %>
<%=link_to('Back to list', pages_controller_index_path(:subject_id => @subject.id), :class => 'back-line') %>
<div class="page new">
  <h2>Create Page</h2>
    <%=form_for(@page, :url => pages_controller_index_path(:subject_id => @subject.id)) do |f| %>
      <%= render(:partial => 'form', :locals => {:f => f})%>
      <div class="form-buttons">
        <%= f.submit("Create Page")%>
      </div>
    <% end %>
</div>

app/views/pages_controller/show.html.erb
<% @page_title = "Show Page" %>
<%=link_to('Back to list', pages_controller_index_path(:subject_id => @subject.id), :class => 'back-line') %>
<div class="page show">
    <h2>Show Page</h2>
    <table summary="Show page view">
        <tr>
          <th>Name</th>
          <td><%= @page.name%></td>
        </tr>
        <tr>
          <th>Subject Name</th>
          <td><%=Subject.find_by_id(@page.subject_id).name if @page.subject_id%></td>
        </tr>
        <tr>
          <th>Permalink</th>
          <td><%= @page.permalink%></td>
        </tr>
        <tr>
          <th>Position</th>
          <td><%= @page.position%></td>
        </tr>
        <tr>
          <th>Visible ?</th>
          <td><%= @page.visible ? 'True': 'False' %></td>
        </tr>
        <tr>
          <th>Created at</th>
          <td><%= @page.created_at%></td>
        </tr>
        <tr>
          <th>Updated at</th>
          <td><%= @page.updated_at%></td>
        </tr>
    </table>
</div>