config/routes.rb
Rails.application.routes.draw do


  root :to => 'public#index'

  get 'show/:permalink', :to => 'public#show', :as => 'public_show'


  # get 'admin_users/index'
  # get 'admin_users/new'
  # get 'admin_users/edit'
  # get 'admin_users/delete'

  get 'admin', :to => 'access#menu'
  get 'access/menu'
  get 'access/login'
  post 'access/attempt_login'
  get 'access/logout'

  resources :admin_users, :except => [:show] do
      member do
        get :delete
      end
  end

  resources :subjects do
    member do
      get :delete
    end
  end

  resources :pages_controller do
    member do
      get :delete
    end
  end

  resources :sections_controller do
    member do
      get :delete
    end
  end

  get 'example_controller/home'
  get 'example_controller/hall'

  get 'demo/index'
  get 'demo/hello'
  get 'demo/other_hello'
  get 'demo/google'
  get 'demo/escape_output'

  #root 'example_controller#home'

  #This is default route and it may go away on future Rails
  #get ':controller(/:action(/:id))'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/sections_controller_controller.rb
class SectionsControllerController < ApplicationController

  layout 'admin'

  before_action :confirm_logged_in
  before_action :find_page
  before_action :set_section_count, :only => [:new, :create, :edit, :update]

  def index
    @sections = @page.sections.sorted
  end

  def show
    @section = Section.find(params[:id])
  end

  def new
    @section = Section.new(:visible => false)
    @section_count = Section.count + 1
    @pages = Page.sorted
  end

  def create
    @section = Section.new(section_params)
    @section.page = @page
    if @section.save
      flash[:notice] = 'Section created successfully'
      redirect_to(sections_controller_index_path(:page_id => @page.id))
    else
      @section_count = Section.count + 1
      @pages = Page.sorted
      render('new')
    end
  end

  def edit
    @section = Section.find(params[:id])
    @section_count = Section.count
    @pages = Page.sorted
  end

  def update
    @section = Section.find(params[:id])
    if @section.update_attributes(section_params)
      flash[:notice] = "#{@section.name} updated successfully"
      redirect_to(sections_controller_path(@section, :page_id => @page.id))
    else
      @section_count = Section.count
      @pages = Page.sorted
      render('edit')
    end
  end

  def delete
    @section = Section.find(params[:id])
  end

  def destroy
    @section = Section.find(params[:id])
    @section.destroy
    flash[:notice] = "#{@section.name} destroyed successfully."
    redirect_to(sections_controller_index_path(:page_id => @page.id))
  end

  private
  def section_params
    params.require(:section).permit(:name, :position, :visible, :content_type, :content)
  end

  def find_page
    @page = Page.find(params[:page_id])
  end

  def set_section_count
    @section_count = @page.sections.count
    if params[:action] == 'new' || params[:action] == 'create'
      @section_count += 1
    end
  end

end

app/helpers/sections_controller_helper.rb
module SectionsControllerHelper
end

app/views/sections_controller/_form.html.erb
<%= error_messages_for(f.object)%>

<table summary = "Section Form Fields">
  <tr>
    <th>Name</th>
    <td><%= f.text_field(:name)%></td>
  </tr>
  <tr>
    <th>Page</th>
    <td><%= f.object.page.name%></td>
  </tr>
  <tr>
    <th>Position</th>
    <td><%= f.select(:position, 1..@section_count)%></td>
  </tr>
  <tr>
    <th>Visible</th>
    <td><%= f.check_box(:visible)%></td>
  </tr>
  <tr>
    <th>Content Type</th>
    <td><%= f.radio_button(:content_type, 'text')%> TEXT</td><br>
    <td><%= f.radio_button(:content_type, 'HTML')%> HTML</td>
  </tr>
  <tr>
    <th>Content</th>
    <td><%= f.text_area(:content, :size => '40x10')%></td>
  </tr>
</table>

app/views/sections_controller/delete.html.erb
<% page_title = "Delete Section" %>
<%=link_to('Back to list', sections_controller_index_path(:page_id => @page.id), :class => 'back-line') %>

<div class="sections delete">
  <h2>Delete Section</h2>
  <%= form_for(@section, :url => sections_controller_path(:page_id => @page.id), :method => 'delete') do |f|%>
  <p>Are you sure you want to permanently delete this section ?</p>
  <p class="reference-name"><%=f.object.name%></p>
  <div class="form-button">
    <%=f.submit("Delete section")%>
  </div>
  <%end%>
</div>

app/views/sections_controller/edit.html.erb
<% page_title = "Edit Section" %>
<%=link_to('Back to list', sections_controller_index_path, :class => 'back-line') %>
<div class="section new">
  <h2>Edit Section</h2>
    <%=form_for(@section, :url => sections_controller_path) do |f| %>

      <%= render(:partial => 'form', :locals => {:f => f})%>
      <div class="form-buttons">
        <%= f.submit("Update Section")%>
      </div>
    <% end %>
</div>

app/views/sections_controller/index.html.erb
<% page_title = "All Sections" %>

<%= link_to("<< Back to Pages", pages_controller_index_path(:subject_id => @page.subject_id)) %>

<div class="sections index">
  <h2>Sections</h2>
  <%=link_to("Add new section",new_sections_controller_path(:page_id => @page.id),:class => 'action new')%>
  <table class="listing" summary="Sections List">
    <tr class="header">
      <th>#</th>
      <th>Page ID</th>
      <th>Name</th>
      <th>Visible</th>
      <th>Action</th>
    </tr>
    <% @sections.each do |section| %>
    <tr>
      <td><%= section.position %></td>
      <td><%= section.page_id%></td>
      <td><%= section.name%></td>
      <td><%= status_tag(section.visible) %></td>
      <td class="actions">
          <%=link_to("Show", sections_controller_path(section, :page_id => @page.id), :class => 'action_show') %>
          <%=link_to("Edit", edit_sections_controller_path(section, :page_id => @page.id), :class => 'action_edit') %>
          <%=link_to("Delete", delete_sections_controller_path(section, :page_id => @page.id), :class => 'action_delete') %>
      </td>
    </tr>
    <% end %>
  </table>
</div>

app/views/sections_controller/new.html.erb
<% page_title = "New Section" %>
<%=link_to('Back to list', sections_controller_index_path(:page_id => @page.id), :class => 'back-line') %>
<div class="section new">
  <h2>Create Section</h2>
    <%=form_for(@section, :url => sections_controller_index_path(:page_id => @page.id)) do |f| %>

            <%= render(:partial => 'form', :locals => {:f => f})%>
            <div class="form-buttons">
        <%= f.submit("Create Section")%>
      </div>
    <% end %>
</div>

app/views/sections_controller/show.html.erb
<% page_title = "Show Section" %>
<%=link_to('Back to list', sections_controller_index_path(:page_id => @page.id), :class => 'back-line') %>
<div class="page show">
    <h2>Show Section</h2>
    <table summary="Show section view">
        <tr>
          <th>Name</th>
          <td><%= @section.name%></td>
        </tr>
        <tr>
          <th>Page Name</th>
          <td><%=Page.find_by_id(@section.page_id).name if @section.page_id%></td>
        </tr>
        <tr>
          <th>Position</th>
          <td><%= @section.position%></td>
        </tr>
        <tr>
          <th>Visible ?</th>
          <td><%= @section.visible ? 'True': 'False' %></td>
        </tr>
        <tr>
          <th>Content Type</th>
          <td><%=@section.content_type%></td>
        </tr>
        <tr>
          <th>Content</th>
          <td><%=@section.content%></td>
        </tr>
        <tr>
          <th>Created at</th>
          <td><%= @section.created_at%></td>
        </tr>
        <tr>
          <th>Updated at</th>
          <td><%= @section.updated_at%></td>
        </tr>
    </table>
</div>